apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "jwt-example"
spec:
  targets:
  - name: hello
  peers:
  - mtls: {}
  origins:
  - jwt:
      issuer: "http-echo@http-echo.kubernetes.killabayte.com"
      jwksUri: "http://auth.kubernetes.killabayte.com/.well-known/jwks.json"
  principalBinding: USE_ORIGIN
---
